### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [mlaanderson/coffeecat#8]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by mlaanderson** [comment]
Sorry for the late reply, I was away on business.

I'll investigate Template Literal. The nice thing about CoffeeCat is that it can use whichever template engine you wish. The applets/containers are separate Express applications that get mounted at startup and define their own template engines, etc.

The one exception to that is the error page. However, if you have a catch-all route in your application then the server error page will not be used except for requests for which there is no matching applet.

I suspect it would be better to let the user define the template engine used for the error template.

I'll keep this open until I look into that.

**Comment by mlaanderson** [comment]
It looks like Template Literal isn't ready to be dropped in as an Express template engine.
